apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
data:
  index.html: | 
    <!doctype html>  
    <html>  
      <head>  
        <meta charset="utf-8">  
        <title>Terraform k8's CICD</title> 
      </head>
      <body
      <h1>Terraform demo</h2> 
      </body>
    </html>

